site_name: RecHr
site_description: RecHr
site_author: Dejan Ljubobratović
repo_url: https://github.com/DejanLjubobratovic/rechr-website/
edit_uri: blob/main/docs/

nav:
  - About: 



# Theme settings
theme:
  name: material
  palette:
    scheme: slate
    primary: teal
    accent: teal
  custom_dir: overrides
  features:
    - header.autohide
    - navigation.instant
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tracking
  logo: images/rec-logo.jpg
  favicon: images/favicon.png
  language: hr
