site_name: RecHr
repo_url: https://github.com/DejanLjubobratovic/rechr-website/
edit_uri: blob/main/docs/




# Theme settings
theme:
  name: material
  palette:
    scheme: slate
    primary: teal
    accent: teal
