#General info
site_name: RecHr
site_description: RecHr
site_author: Dejan Ljubobratović
repo_url: https://github.com/DejanLjubobratovic/rechr-website/
edit_uri: blob/main/docs/
          
#Navigation
nav:
  - About: 
    - index.md
  - Nastava: 
    - nastava/index.md
    - Kolegiji:
      - Dubinska analiza podataka: nastava/kolegiji/DAP.md
      - Programiranje 1: nastava/kolegiji/PROG1.md
      - Programiranje 2: nastava/kolegiji/PROG2.md
      - Algoritmi i strukture podataka: nastava/kolegiji/ASP.md
      - Inteligentni sustavi 2: 
        - nastava/kolegiji/IS2/01_Colab_osnove.ipynb
        - nastava/kolegiji/IS2/02_R_osnove.ipynb
        - nastava/kolegiji/IS2/03_R_Matrice.ipynb
        - nastava/kolegiji/IS2/04_R_Faktori.ipynb
        - nastava/kolegiji/IS2/05_R_DataFrame.ipynb
        - nastava/kolegiji/IS2/06_R_Filtriranje_sort.ipynb
        - nastava/kolegiji/IS2/07_R_Vizualizacija_podataka.ipynb
        - nastava/kolegiji/IS2/08_R_Iris_projekt.ipynb
# Plugin settings
plugins:
  - mkdocs-jupyter

# Theme settings
theme:
  name: material
  palette:
    scheme: slate
    primary: teal
    accent: teal
  features:
    - header.autohide # Dodaje "back to top" gumb
    - navigation.instant
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
  logo: images/rec-logo.jpg
  favicon: images/favicon.png
  language: hr
markdown_extensions:  
  - pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji
    emoji_generator: !!python/name:materialx.emoji.to_svg
