#General info
site_name: RecHr
site_description: RecHr
site_author: Dejan Ljubobratović
repo_url: https://github.com/DejanLjubobratovic/rechr-website/
edit_uri: blob/main/docs/
          
#Navigation
nav:
  - About: 
    - index.md
  - Nastava: 
    - nastava/index.md
    - Kolegiji:
      - Dubinska analiza podataka: nastava/kolegiji/DAP.md
      - Programiranje 1: nastava/kolegiji/PROG1.md
      - Programiranje 2: nastava/kolegiji/PROG2.md
      - Algoritmi i strukture podataka: nastava/kolegiji/ASP.md

# Theme settings
theme:
  name: material
  palette:
    scheme: slate
    primary: teal
    accent: teal
  custom_dir: overrides
  features:
    - header.autohide # Dodaje "back to top" gumb
    - navigation.instant
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
  logo: images/rec-logo.jpg
  favicon: images/favicon.png
  language: hr
